<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_EmailPasswordLogin</name>
   <tag></tag>
   <elementGuidId>3613bb1c-d184-4211-a2eb-7eac80d4e335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.space-y-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;EmailPasswordLogin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>59af7682-cd30-40ee-b83e-002392f7fd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>space-y-6</value>
      <webElementGuid>74d25296-5ffd-4212-8acc-c0e9279a4f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EmailPasswordLogin</value>
      <webElementGuid>9d28d3b3-fcbd-497e-8ab6-98b390ee082b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-[#121212] text-white min-h-screen&quot;]/div[@class=&quot;relative min-h-screen&quot;]/section[@class=&quot;relative flex items-center justify-center py-24 px-6 md:px-16&quot;]/div[@class=&quot;w-full max-w-md bg-[#1a1a1a] rounded-xl p-8 shadow-lg transform transition-all duration-500 hover:shadow-2xl hover:shadow-[#703BF7]/20&quot;]/form[@class=&quot;space-y-6&quot;]</value>
      <webElementGuid>3abb9039-ccde-4a9e-b49c-8fbebbf3ae1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/form</value>
      <webElementGuid>c32220c5-16e6-406a-9794-43747eb3ed82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::form[1]</value>
      <webElementGuid>b787cb98-696b-4520-b227-7474e2dfbb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[2]/following::form[1]</value>
      <webElementGuid>56843a84-4d1e-46dd-ba61-6338f50853dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>d9c907c6-6336-424d-8ea2-1ba381fe634f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'EmailPasswordLogin' or . = 'EmailPasswordLogin')]</value>
      <webElementGuid>378537e0-2b8b-46dd-9a24-8beebfa34c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
