<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reviews</name>
   <tag></tag>
   <elementGuidId>8fb6240f-4183-4db4-b72d-9fac25218819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/nav/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Reviews&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d781b8d-2af9-4e74-873a-2343e5da841a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-4 py-3 mt-2 text-base rounded-lg transition-colors duration-200 text-gray-300 hover:text-white hover:bg-gray-800</value>
      <webElementGuid>c1a5c268-7ef9-4c4a-a70a-01643ff04953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/reviews</value>
      <webElementGuid>6f633a01-9b43-4fd3-a228-80c10b2fe539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e39a7be9-11e8-4635-8031-bf55f5b114fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reviews</value>
      <webElementGuid>3e608abb-bacf-417b-96a1-c9faa653359b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-[#0f0f0f]&quot;]/div[@class=&quot;fixed top-20 bottom-0 left-0 z-[45] w-64 transform bg-[#1a1a1a] shadow-lg transition-transform duration-300 ease-in-out lg:translate-x-0 border-r border-gray-800 -translate-x-full&quot;]/nav[@class=&quot;mt-4 px-2&quot;]/a[@class=&quot;flex items-center px-4 py-3 mt-2 text-base rounded-lg transition-colors duration-200 text-gray-300 hover:text-white hover:bg-gray-800&quot;]</value>
      <webElementGuid>adf727a1-8b6a-4ea9-9605-24d1df78bec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/nav/a[3]</value>
      <webElementGuid>dd653678-de94-4256-949f-dea7e33a0033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reviews')]</value>
      <webElementGuid>eeed102a-71a0-4a9c-87f2-cdfe72a1e541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properties'])[1]/following::a[1]</value>
      <webElementGuid>9b0c98ac-9d97-49ec-b1d2-5358345e8d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[2]</value>
      <webElementGuid>8feadd7d-0ded-49eb-a920-f425783893f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/preceding::a[1]</value>
      <webElementGuid>b81d69ab-6888-49a2-ad77-471aac9827d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AD'])[1]/preceding::a[2]</value>
      <webElementGuid>214c12c2-dfc1-4d7e-a88c-8c8ef5874b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reviews']/parent::*</value>
      <webElementGuid>8e0890d8-0a78-4080-9189-447873e16901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/reviews')]</value>
      <webElementGuid>bd19a743-f175-439c-8525-3eca0f61039d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a[3]</value>
      <webElementGuid>e2d96c9e-3a02-46c6-aa23-cf3a1c07f2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/reviews' and (text() = 'Reviews' or . = 'Reviews')]</value>
      <webElementGuid>9a7f9268-a418-4653-9f3d-0cb474f0cce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
