<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Edit button to enable profile form editing</description>
   <name>editButton</name>
   <tag></tag>
   <elementGuidId>edit-button-profile-001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id="root"]/div/div/div[2]/div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edit-btn-001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id="root"]/div/div/div[2]/div[1]/button</value>
      <webElementGuid>edit-btn-002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
